var $lang={
tdName: "Your Name:",
tdEmail: "E-mail:",
tdEmailConfirm:"E-mail Confirm:",
tdPhone: "Phone/WhatsApp:",
tdCompanyName: "Company:",
tdTitle: "Subject:",
tdContent: "Content",
tdstips: "Please input your email here, it is very important!",
tdxtips: "Please include details like size, weight, destination port and etc., so that we can quote the best price.",
btnSubmit: "Send",
msgTooLongName: "The name of the number of characters can not be more than 400",
msgInputName: "Please enter the your name",
msgInputPhone: "Please enter the phone/WhatsApp",
msgInputCompany: "Please enter the company",
msgInputTitle: "Please enter the subject",
msgInputEmail: "Please enter the email",
msgCheckEmail: "Please enter a valid email format",
msgCheckEmailConfirm: "Two email inconsistencies",
msgTooLongTitle: "The subject of the number of characters can not be more than 340!",
msgInputContent: "Please enter the content!",
msgTooLongContent: "Contents of the number of characters can not be more than 2000!",
txtSubmit: "Is being submitted...",
tdChange: "Another",
tdVerification: "Verification Code:",
msgInputVerification: "Please enter verification code",
msgCheckVerification: "Verification code error",
msgSendFailed: "Send failed, please re submit!",
msgSendSucess: "Sent successfully, we will contact you soon!",
msgSameContent: "Please don't send the same inqury again!",
msgFrequentlyContent: "Send failure, send too frequently!",
msgSensitiveContent: "Send failed, content containing sensitive words!",
defaultprompt:"Quick reply selection"
}